### ISSUE TITLE
plot graph with dot

### ISSUE THREAD

**Issue by kexul** [michellab/bss_fep_advanced_tut_bg#1]
Hi, I've seen your discussion here https://github.com/michellab/BioSimSpace/issues/193 , @JenkeScheen said:

> if you've done any work on LOMAP network generation to show within a notebook that would be very helpful! It's starting to look like the LOMAP build I currently have is unable to draw a decent-looking network to show in an ipynb.

The network drawn by `pygraphviz` has several drawbacks: 
       1. The edge would be covered by molecule image. 
       2. The molecule image would cover each other when there are many molecule pairs. 
I would recommend use `dot` to generate network graph as LOMAP have done, which doesn't have the drawbacks listed above. 
I've copied some code from my project and created a gist to show how to do that with several lines: 
 https://gist.github.com/kexul/044340c773822c7748c722b9e2e082e2

Core lines:
1. Add image file and label, here `labelloc='t'` means label is at top of node. 
```
G.add_node(name, image=fname, label = name, labelloc='t')
```
2. Generate `.dot` file and convert it to `.png`.
```
nx.nx_agraph.write_dot(G, f'temp/{file_name}.dot')
os.system(f'dot -Tpng temp/{file_name}.dot -o temp/{file_name}.png')
````

![image](https://user-images.githubusercontent.com/5920217/115953018-cc95c700-a51b-11eb-8657-54b8189a7beb.png)

**Comment by lohedges** [comment]
Thanks, @kexul. This is very helpful. I agree that the network plot quickly becomes a mess as the number of ligand pairs grow. This seems like a great approach and will be easy to implement.

**Comment by JenkeScheen** [comment]
Ah! LOMAP generates a dot plot too, there should be a file in the work-dir, that could save us some work. I remember looking at the saved image during early dev and not liking it, but I think that must have been because we were only generating partial graphs at that point. Thanks for the suggestion @kexul!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
